desmos tx staking create-validator \
--amount=3000000udsm \
--pubkey=$(desmos tendermint show-validator) \
--moniker=<MONIKER> \
--chain-id=desmos-mainnet \
--commission-rate="0.10" \
--commission-max-rate="0.20" \
--commission-max-change-rate="0.01" \
--min-self-delegation="1" \
--gas="auto" \
--gas-adjustment="1.2" \
--gas-prices="0.025udsm" \
--from=<WALLET_NAME>
